<!-- Footer from index.html -->
    <footer>
        <p><a href="https://cos10026group4.atlassian.net/jira/software/projects/SCRUM/summary">Jira Project</a></p>
        <p><a href="https://106514992.github.io/COS10026-Applied-Web-Project-Part-1-of-2/index.html">Live site link</a>
        </p>
        <p><a href="https://github.com/106514992/COS10026-Applied-Web-Project-Part-1-of-2">GitHub Repository</a></p>
        <p><a href="mailto:info@mediaflare.com.au"
                aria-label="Email us at info@mediaflare.com.au">info@mediaflare.com.au</a></p>
    </footer>


</body>
</html>