<!-- Navigation -->
<nav aria-label="Main navigation">
    <a href="jobs.php"><img src="assets/mediaflare_logo.svg" alt="MediaFlare logo" height="40" /></a>

    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Job Description</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About</a></li>
        <li class="align-right"><a href="manage.php">Manage</a></li>
        <li><a href="logout.php">Log out</a></li>
    </ul>
</nav>