    <?php

    // Block direct access to this page - must be a POST request from the form
    if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !isset($_POST['job_reference'])) {
        header('Location: apply.php');
        exit;
    }
    // Sanitise Inputs
    // Trims whitespace and converts special characters to safe HTML chars
    function sanitise($value) {
        return htmlspecialchars(trim($value));
    }

    // Pull each field out of $_POST and sanitise it straight away
    $job_reference  = sanitise($_POST['job_reference']);
    $first_name     = sanitise($_POST['first_name']);
    $last_name      = sanitise($_POST['last_name']);
    $date_of_birth  = sanitise($_POST['date_of_birth']);
    $gender         = sanitise($_POST['gender']);
    $street_address = sanitise($_POST['street_address']);
    $suburb         = sanitise($_POST['suburb']);
    $state          = sanitise($_POST['state']);
    $postcode       = sanitise($_POST['postcode']);
    $email          = sanitise($_POST['email']);
    $phone          = sanitise($_POST['phone']);
    $other_skills   = sanitise($_POST['other_skills']);

    // Skills come in as an array from the checkboxes (name="skills[]")
    $skills_str = implode(',', $_POST['skills'] ?? []);

    // Validate
    // Check every field and collect problems into $errors.
    // If it's not empty at the end, redirect back to the form.
    $errors = [];

    if ($job_reference === '' || !preg_match('/^[A-Za-z0-9]{5}$/', $job_reference))
        $errors[] = 'Job reference must be exactly 5 alphanumeric characters.';

    if ($first_name === '' || !preg_match('/^[A-Za-z]{1,20}$/', $first_name))
        $errors[] = 'First name is required and must be letters only, up to 20 characters.';

    if ($last_name === '' || !preg_match('/^[A-Za-z]{1,20}$/', $last_name))
        $errors[] = 'Last name is required and must be letters only, up to 20 characters.';

    // Check date matches dd/mm/yyyy format
    if (!preg_match('/^\d{2}\/\d{2}\/\d{4}$/', $date_of_birth))
        $errors[] = 'Date of birth must be in dd/mm/yyyy format.';

    if (!in_array($gender, ['male', 'female', 'prefer-not-to-say']))
        $errors[] = 'Please select a gender.';

    if ($street_address === '')
        $errors[] = 'Street address is required.';

    if ($suburb === '')
        $errors[] = 'Suburb is required.';

    if (!in_array($state, ['VIC','NSW','QLD','NT','WA','SA','TAS','ACT']))
        $errors[] = 'Please select a state.';

    if (!preg_match('/^[0-9]{4}$/', $postcode))
        $errors[] = 'Postcode must be exactly 4 digits.';

    if (!filter_var($email, FILTER_VALIDATE_EMAIL))
        $errors[] = 'Please enter a valid email address.';

    if (!preg_match('/^[0-9]{8,12}$/', $phone))
        $errors[] = 'Phone must be 8 to 12 digits, numbers only.';

    if (empty($_POST['skills']))
        $errors[] = 'Please select at least one skill.';

    // If anything failed, redirect back to the form
    if (!empty($errors)) {
        header('Location: apply.php');
        exit;
    }

    // Connect to the database
    require_once 'settings.php';

    $conn = new mysqli($host, $username, $password, $dbname);

    if ($conn->connect_error)
        die('Database connection failed: ' . htmlspecialchars($conn->connect_error));

    // Insert the record directly using sanitised values
    $sql = "INSERT INTO `eoi`
        (job_reference, first_name, last_name, date_of_birth, gender,
        street_address, suburb, state, postcode, email, phone, skills, other_skills)
        VALUES
        ('$job_reference', '$first_name', '$last_name', '$date_of_birth', '$gender',
        '$street_address', '$suburb', '$state', '$postcode', '$email', '$phone', '$skills_str', '$other_skills')";

    if (!$conn->query($sql))
        die('Insert failed: ' . htmlspecialchars($conn->error));

    // Grab the auto-generated EOI number so we can show it on the confirmation page
    $eoi_number = $conn->insert_id;

    $conn->close();

    // Confirmation page
    // Everything went fine, so show a success page using the shared includes.
    $pageTitle = "Application Submitted - MediaFlare";
    $pageStyles = '<link rel="stylesheet" href="style/style.css" />';

    include "header.inc";
    ?>

    <?php include "nav.inc"; ?>

    <main>
        <div class="confirmation-box">
            <h1>Application Submitted</h1>
            <p>Thank you, <?php echo htmlspecialchars($first_name . ' ' . $last_name); ?>. Your expression of interest has been received.</p>
            <!-- The EOI number was auto-generated by the database on insert -->
            <div class="eoi-number">EOI #<?php echo (int)$eoi_number; ?></div>
            <p>Please keep your EOI number for your records. We will be in touch at <strong><?php echo htmlspecialchars($email); ?></strong>.</p>

            <!-- A quick summary of everything that was submitted -->
            <table class="summary-table">
                <tr><th>Job Reference</th><td><?php echo htmlspecialchars($job_reference); ?></td></tr>
                <tr><th>Name</th><td><?php echo htmlspecialchars($first_name . ' ' . $last_name); ?></td></tr>
                <tr><th>Date of Birth</th><td><?php echo htmlspecialchars($date_of_birth); ?></td></tr>
                <tr><th>Gender</th><td><?php echo htmlspecialchars(ucfirst(str_replace('-', ' ', $gender))); ?></td></tr>
                <tr><th>Address</th><td><?php echo htmlspecialchars("{$street_address}, {$suburb} {$state} {$postcode}"); ?></td></tr>
                <tr><th>Email</th><td><?php echo htmlspecialchars($email); ?></td></tr>
                <tr><th>Phone</th><td><?php echo htmlspecialchars($phone); ?></td></tr>
                <tr><th>Skills</th><td><?php echo htmlspecialchars(str_replace(',', ', ', $skills_str)); ?></td></tr>
                <?php if ($other_skills !== ''): ?>
                <tr><th>Other Skills</th><td><?php echo htmlspecialchars($other_skills); ?></td></tr>
                <?php endif; ?>
                <tr><th>Status</th><td>New</td></tr>
            </table>

            <a href="apply.php">Submit another application</a>
        </div>
    </main>

    <?php include "footer.inc"; ?>